### ISSUE TITLE
Rename folders to have Domain name.

### ISSUE THREAD

**Issue by arush-sal** [DevOps-Academy-Org/dca-prep-guide#25]
Currently, the folders are named as "domain1", "domain2", etc. Instead of this, I propose that it should be renamed to something like "Domain 1 - Orchestration", "Domain 2 - Image Creation, Management, and Registry".
As that way, it will be easier for anyone to browse through the directory knowing the topics that particular directory/domain covers.

**Comment by Govinda-Fichtner** [comment]
@arush-sal Sound like a good idea. Wanna give me a hand and prepare a PR?

**Comment by arush-sal** [comment]
Definitely. Let me send the PR.

Regards
